#
# Blog Settings
#
author: Sisly
description: Et glimt af hverdagens køkken
url: http://www.sisly.dk
title: SISLY.DK
subtitle: Et glimt af hverdagens køkken
gravatar_url: https://2.gravatar.com/avatar/0
subscribe_rss: http://feeds.haacked.com/0

# Github repositories
github_user: sisly
github_repo_url: https://github.com/Sisly/sisly.dk/

# Disqus Comments
disqus_short_name: sisly
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: 0


#
# Jekyll Settings
#
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
permalink: /arkiv/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories

gems:
  - jekyll-redirect-from
  - jekyll-sitemap